PAPER_CAPITAL_INR = 10_000.0
RISK_PER_TRADE = 0.01
MAX_LEVERAGE = 3.0

# CoinDCX / FX
USDT_INR_PAIR_CANDIDATES = ["USDTINR", "I-USDT_INR"]
USDT_INR_FALLBACK_RATE = 87.0
USDT_INR_CACHE_SECONDS = 300
FUTURES_MARGIN_CURRENCY = "USDT"

# Universe / liquidity
CANDLE_LIMIT_5M = 300
MIN_VALID_5M_CANDLES = 285
MAX_GAP_MINUTES = 15
MIN_TRADED_VALUE_INR_24H = 5_000_000.0
MAX_SPREAD_PCT = 0.15
ABNORMAL_ATR_MULT = 5.0
ACTIVE_INSTRUMENTS_REFRESH_SECONDS = 6 * 60 * 60
LIQUIDITY_WHITELIST_REFRESH_SECONDS = 30 * 60
UNIVERSE_REQUEST_PAUSE_SECONDS = 0.03

# Precision V3 scan
SCAN_SECONDS = 60
IDLE_LOOP_SECONDS = 1
OPEN_POSITION_MONITOR_SECONDS = 2
ARMED_SETUP_MONITOR_SECONDS = 2
ARMED_SETUP_TIMEOUT_SECONDS = 10 * 60
MAX_ARM_DISTANCE_ATR = 0.35

# Indicators
ATR_PERIOD = 14
RSI_PERIOD = 14
EMA_FAST = 20
EMA_SLOW = 50
EMA_TREND = 200
SWING_LEFT = 2
SWING_RIGHT = 2

# V3 hard gates: score NEVER overrides these
MIN_PRECISION_SCORE = 78
MIN_TREND_GAP_ATR = 0.10
MIN_EMA_SLOPE_ATR = 0.03
MAX_EMA_EXTENSION_ATR = 1.25

# Consolidation rejection
CONSOLIDATION_LOOKBACK = 12
MAX_CONSOLIDATION_RANGE_ATR = 3.0
MAX_EMA_CROSSES_IN_LOOKBACK = 4
MIN_DIRECTIONAL_EFFICIENCY = 0.28

# Impulse + Fibonacci pullback
IMPULSE_LOOKBACK = 30
MIN_IMPULSE_ATR = 2.2
FIB_MIN = 0.382
FIB_MAX = 0.618
FIB_TOLERANCE_ATR = 0.15

# Confirmation candle / sweep
MIN_CONFIRM_BODY_ATR = 0.20
MIN_CONFIRM_RANGE_ATR = 0.55
MIN_CONFIRM_CLOSE_LOCATION = 0.65
MIN_REJECTION_WICK_BODY = 0.70
MIN_CONFIRM_VOLUME_RATIO = 0.80
SWEEP_LOOKBACK = 5
TRIGGER_BUFFER_ATR = 0.03

# Momentum context, not a blind trigger
LONG_RSI_MIN = 42
LONG_RSI_MAX = 68
SHORT_RSI_MIN = 32
SHORT_RSI_MAX = 58

# Entry quality
MIN_RR_TO_STRUCTURE = 1.80
MIN_STOP_ATR = 0.55
MAX_STOP_ATR = 2.20
STRUCTURE_TARGET_LOOKBACK = 40

# Exit lifecycle
BE_TRIGGER_R = 1.0
TRAIL_TRIGGER_R = 1.5
LOCK_TRIGGER_R = 2.0
LOCK_MIN_R = 1.0
TRAIL_ATR_MULT = 1.0
REVERSAL_BODY_ATR_MULT = 1.25
REVERSAL_VOLUME_MULT = 2.0

# Paper execution assumptions
ASSUMED_FEE_RATE_PER_SIDE = 0.0005
ASSUMED_SLIPPAGE_RATE_PER_SIDE = 0.0005
